version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hospital_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: hospital_db
    ports:
      - "5433:5432"   # Your DB is on port 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- ADD THIS SECTION BELOW ---
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  # ------------------------------

volumes:
  pgdata: